# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-19 06:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to='')),
                ('text', models.TextField(blank=True)),
                ('added_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
